# Generated by Django 6.0.4 on 2026-04-17 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Genre',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Artiste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('bio', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='artistes/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('abonnes', models.ManyToManyField(blank=True, related_name='artistes_suivis', to=settings.AUTH_USER_MODEL)),
                ('utilisateur', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artiste', to=settings.AUTH_USER_MODEL)),
                ('genres', models.ManyToManyField(blank=True, to='music.genre')),
            ],
            options={
                'verbose_name': 'Artiste',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('date_sortie', models.DateField()),
                ('type_album', models.CharField(choices=[('album', 'Album'), ('ep', 'EP'), ('single', 'Single')], default='album', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('artiste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='music.artiste')),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.genre')),
            ],
            options={
                'verbose_name': 'Album',
                'ordering': ['-date_sortie'],
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='playlists/')),
                ('description', models.TextField(blank=True)),
                ('est_publique', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Playlist',
                'ordering': ['-date_modification'],
            },
        ),
        migrations.CreateModel(
            name='ProfilUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('bio', models.TextField(blank=True)),
                ('abonne_premium', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('genres_favoris', models.ManyToManyField(blank=True, to='music.genre')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Titre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('fichier_audio', models.FileField(upload_to='audio/')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('duree', models.PositiveIntegerField(default=0, help_text='Durée en secondes')),
                ('numero_piste', models.PositiveIntegerField(default=1)),
                ('paroles', models.TextField(blank=True)),
                ('nb_ecoutes', models.PositiveIntegerField(default=0)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('est_explicite', models.BooleanField(default=False)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titres', to='music.album')),
                ('artiste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titres', to='music.artiste')),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.genre')),
            ],
            options={
                'verbose_name': 'Titre',
                'ordering': ['album', 'numero_piste', 'titre'],
            },
        ),
        migrations.CreateModel(
            name='PlaylistTitre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.playlist')),
                ('titre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.titre')),
            ],
            options={
                'ordering': ['ordre'],
                'unique_together': {('playlist', 'titre')},
            },
        ),
        migrations.AddField(
            model_name='playlist',
            name='titres',
            field=models.ManyToManyField(blank=True, through='music.PlaylistTitre', to='music.titre'),
        ),
        migrations.CreateModel(
            name='Historique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ecoute', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to=settings.AUTH_USER_MODEL)),
                ('titre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.titre')),
            ],
            options={
                'ordering': ['-date_ecoute'],
            },
        ),
        migrations.CreateModel(
            name='FavoriTitre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris_titres', to=settings.AUTH_USER_MODEL)),
                ('titre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to='music.titre')),
            ],
            options={
                'unique_together': {('utilisateur', 'titre')},
            },
        ),
    ]
