# Generated by Django 6.0.4 on 2026-04-19 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeDeezer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deezer_id', models.CharField(max_length=50)),
                ('titre', models.CharField(max_length=200)),
                ('artiste', models.CharField(max_length=200)),
                ('cover', models.URLField(blank=True)),
                ('preview', models.URLField(blank=True)),
                ('duree', models.PositiveIntegerField(default=0)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_deezer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_ajout'],
                'unique_together': {('utilisateur', 'deezer_id')},
            },
        ),
    ]
