# Generated by Django 6.0.4 on 2026-04-20 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_likedeezer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='likedeezer',
            name='artiste',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='likedeezer',
            name='cover',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='likedeezer',
            name='preview',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='likedeezer',
            name='titre',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.CreateModel(
            name='CommentaireDeezer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deezer_artiste_id', models.CharField(max_length=50)),
                ('artiste_nom', models.CharField(default='', max_length=200)),
                ('contenu', models.TextField(default='')),
                ('note', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires_deezer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
